@startuml

title クラス図

Class SerialManager {
	-void Receive(byte data)
	+bool WriteData<StructT>(StructT dataStruct)
	+bool ReadData(out OutputSignalData output)
	+bool ReadData(out InputSignalData output)
	-object LockObject
	-InputSignalData RecentInputSignal
	-OutputSignalData RecentOutputSignal
}


Class SerialState {
	
	+void Receive(byte data)
	-byte[] buff

}

Class HeaderState {
	+void Receive(byte data)
}

Class HeaderDataState{
	+void Receive(byte data)
}

Class InputDataState {
	+void Receive(byte data)
}

Class OutputDataState {
	+void Receive(byte data)}
}


SerialManager "1" -> "1" SerialState
SerialManager "1" <- "1" SerialState


SerialState <|-- HeaderState
SerialState <|-- HeaderDataState
SerialState <|-- InputDataState
SerialState <|-- OutputDataState


@enduml