@startuml

title ブロック並べ関連クラス図

Class ブロック運搬ルール{
	-五角形を構成するブロック置き場のNo
	+次の運搬対象ブロックと運搬先置き場の決定()
	+運搬経路の決定()
}

class 置き場{
	+No
	+ 色
	+座標
	+他の置き場との距離()
	+走行体との距離()
}

class 走行体{
	+運搬状態 : 運搬中orそれ以外
	+座標
}

class ブロック{
	+ 色
}

class ウェイポイント{
	+始点置き場No
	+終点置き場No
	+座標
}

ブロック運搬ルール "1" --> "15" 置き場
ブロック運搬ルール "1" --> "1" 走行体
ブロック運搬ルール "1" --> "26" ウェイポイント
置き場 "1" --> "0..1"ブロック


@enduml