@startuml
title <size:18>運搬先ブロック置き場の決定</size>



partition 運搬先の置き場を決定する {
	:運搬対象のブロックと一致するブロック置き場を探索する;
	if(個数==1) then (true)
		: 合致した置き場を運搬先の置き場とする;
	else if(個数 > 1) then (true)
		: 合致した置き場のうち、\nブロックの座標から最も近い位置のブロック置き場を運搬先の置き場とする;
	else
		: 退避先の置き場を選ぶ;
		: ブロックの座標から最も近い位置のブロック置き場を運搬先の置き場とする;
	endif
}



@enduml