@startuml
title スピード競技中のシーケンス図
hide footbox

戦略管理 -> 入力信号情報 : センサ情報更新()
	activate 入力信号情報
	戦略管理 <-- 入力信号情報 
	deactivate 入力信号情報

戦略管理 -> 入力信号情報 : 左モータ角度取得()
	activate 入力信号情報
	戦略管理 <-- 入力信号情報 
	deactivate 入力信号情報

戦略管理 -> 入力信号情報 : 右モータ角度取得()
	activate 入力信号情報
	戦略管理 <-- 入力信号情報 
	deactivate 入力信号情報

戦略管理 -> 自己位置推定器 : 走行体位置更新(左モータ角度, 右モータ角度)
	activate 自己位置推定器
	戦略管理 <-- 自己位置推定器
	deactivate 自己位置推定器

戦略管理 -> ライントレース戦略: 戦略実行()
	activate ライントレース戦略
	戦略管理 <-- ライントレース戦略

	ライントレース戦略 -> 自己位置推定器 : 走行体位置取得()
		activate 自己位置推定器
		ライントレース戦略 <-- 自己位置推定器
		deactivate 自己位置推定器

	ライントレース戦略 -> ライントレース戦略: 該当する区間のPIDパラメータ取得()
	ライントレース戦略 -> ライントレース戦略: モータ出力値計算()

	ライントレース戦略 -> 出力信号情報: モータ出力値設定()
		activate 出力信号情報
		ライントレース戦略 <-- 出力信号情報	
		deactivate 出力信号情報
	deactivate ライントレース戦略

戦略管理 -> 出力信号情報 : モータ情報出力
	activate 出力信号情報
	戦略管理 <-- 出力信号情報
	deactivate 出力信号情報


@enduml