@startuml

title モニタツールを構成するクラス(抜粋)

 
package ブロック並べ攻略{
        
    class ブロック並べルール導出{
        五角形を構成するブロック置き場のNo
        ブロック並べコマンド生成(初期位置コード)
    }

    ブロック並べルール導出 ..> ブロック並べコマンド

    class ブロック並べコマンド{
        シリアライズ()
    }

    ブロック並べコマンド "1"-->"1..*" ライン 
    ブロック並べコマンド "1"-->"2" 置き場

    class 置き場{
        No
        置き場色
        座標
        他の置き場との距離()
        走行体との距離()
    }

    ブロック並べルール導出  "1" -->"26" ライン 
    class ライン{
        始点置き場No
        終点置き場No
        ウェイポイント座標
    }

    class ダイクストラ法{
        最短経路算出()
    }

    ブロック並べルール導出 "1" --> "15" 置き場
    ブロック並べルール導出 "1" --> "1" ダイクストラ法
}

package Bluetooth通信{
    class Bluetooth通信管理{
        ブロック並べコマンド送信()
        PIDパラメータ送信()
    }
    
    class PIDパラメータ{
        Pゲイン
        Iゲイン
        Dゲイン
    }

    Bluetooth通信管理 "1" --> "1..*" PIDパラメータ

}

Bluetooth通信管理 "1"--> "1..*" ブロック並べコマンド

package ユーザーインターフェース{
    class メイン画面{
        初期位置コード入力()
        ブロック並べコマンド送信()
        PIDパラメータ設定()
        PIDパラメータ送信()

    }
}


メイン画面 "1" --> "1" Bluetooth通信管理
メイン画面 "1" --> "1" ブロック並べルール導出


@enduml