@startuml

title 走行体ソフトウェアを構成するクラス

package 走行体情報{
    class 入力信号情報{
        センサ情報取得()
    }

    class 出力信号情報{
        モータ情報出力()
    }

    class 自己位置推定器{
        走行体角度
        走行体位置
        自己位置更新()
    }

}



package Bluetooth通信{
    class Bluetooth通信管理{
    } 

    abstract 電文受信ステート{
        データ受信()
    }

    class ヘッダ受信ステート{
        データ受信()
    }

    class PIDパラメータ受信ステート{
        データ受信()
    }

    class ブロック並べコマンド受信ステート{
        データ受信()
    }

    Bluetooth通信管理 "1" --> "1" 電文受信ステート
    電文受信ステート <|-- ヘッダ受信ステート
    電文受信ステート <|-- PIDパラメータ受信ステート
    電文受信ステート <|-- ブロック並べコマンド受信ステート
}

    Bluetooth通信管理 "1" -u-> "1" 出力信号情報
    Bluetooth通信管理 "1" -u-> "1" 入力信号情報


package 競技戦略{
    class 戦略管理 {
    }

    abstract 戦略{
        周期処理()
    }

    class ライントレース戦略{
        周期処理()
    }

    class PIDパラメータ{
        Pゲイン
        Iゲイン
        Dゲイン
    }

    class 縦列駐車戦略{
        周期処理()
    }

    abstract 縦列駐車場ステート{
        移動()

    }

    class 縦列駐車場前へ移動ステート{
        移動()

    }

    class 縦列駐車場内へ移動ステート{
        移動()
    }

    縦列駐車場ステート "1" <-d- "1" 縦列駐車戦略
    縦列駐車場ステート <|-- 縦列駐車場前へ移動ステート
    縦列駐車場ステート <|-- 縦列駐車場内へ移動ステート
    

    class ブロック並べ戦略{
        周期処理()
    }

    abstract ブロック並べステート{
        移動()
    }

    class ブロック確保ステート{
        移動()
    }

    class ブロック運搬ステート{
        次のウェイポイント座標
        移動()
    }

    class ブロック置き場へ移動ステート{
        次のウェイポイント座標
        移動()
    }

    ブロック並べステート "1" <-d- "1" ブロック並べ戦略 
    ブロック並べステート <|-- ブロック確保ステート
    ブロック並べステート <|-- ブロック運搬ステート
    ブロック並べステート <|-- ブロック置き場へ移動ステート  
}

戦略管理 "1"-->"1" 戦略
戦略 <|-- 縦列駐車戦略
ライントレース戦略 "1"-->"1..*" PIDパラメータ
戦略 <|-- ライントレース戦略
戦略 "1" --> "1" 自己位置推定器  
戦略 "1" --> "1" 出力信号情報
戦略 "1" --> "1" 入力信号情報
Bluetooth通信管理 "1" --> "1" 戦略

package ブロック並べ解法{
    class ブロック並べコマンド{
        デシリアライズ()
    }

    戦略 <|-- ブロック並べ戦略
    ブロック並べ戦略 "1"-d->"1..*" ブロック並べコマンド
    ブロック並べコマンド "1"-->"1..*" ライン 
    ブロック並べコマンド "1"-->"2" 置き場

  class 置き場{
        No
        置き場色
        座標
        他の置き場との距離()
        走行体との距離()
    }

        class ライン{
        始点置き場No
        終点置き場No
        ウェイポイント座標
    }
}

@enduml