@startuml
title << ユースケース図 >>

left to right direction

actor   競技者

package システム {
	usecase	スピード競技を攻略する
	usecase	ブロック並べを攻略する
	usecase 初期位置コードを入力する
	usecase ブロックまで移動する
	usecase ブロックを運搬先ポリゴンブロック置き場に運搬する
}

競技者 --> スピード競技を攻略する
競技者 --> ブロック並べを攻略する

ブロック並べを攻略する .-> 初期位置コードを入力する : <<include>>
ブロック並べを攻略する .-> ブロックまで移動する : <<include>>
ブロック並べを攻略する .-> ブロックを運搬先ポリゴンブロック置き場に運搬する : <<include>>

@enduml