

@startuml
title << ゲーム構成要素 >>

object  ブロック{
	# 色
	# 合致
}

object ポリゴンブロック置き場 {
	# 番号
	# 座標
	# 色
}


object ライン{
	# 長さ
	# 角度
}

object プレイヤー {
	# 座標 
}

object フィールド {

}


プレイヤー "1" -d->  "5" ブロック : 運搬対象
プレイヤー "1" -d->  "0..1" ブロック : 運搬中

ブロック "0..1" <- "1" ポリゴンブロック置き場
ブロック "1" -> "0..1" ポリゴンブロック置き場


フィールド "1" -d-> "15" ポリゴンブロック置き場 
フィールド "1" -d-> "25" ライン

ポリゴンブロック置き場 "1" <- "1" ライン : 始点
ポリゴンブロック置き場 "1" <- "1" ライン : 終点

enum 色の種類 {
	青
	黄
	赤
	緑
	黒
}

@enduml