@startuml
title <size:18>ブロック運びフローチャート</size>


start
: 初期位置コードからブロックの配置を求める;

repeat 
	:運搬対象ブロックを決定する;
	:運搬先の置き場を決定する;
	:運搬対象ブロックを確保する;
	:運搬対象ブロックを運搬先まで運ぶ;
	:ブロックの情報と置き場の情報を更新する;
repeat while (全てのブロックの色と置き場の色が一致している);
stop


partition 運搬対象ブロックを決定する {
	:運搬可能なブロックを探索する;
	if(個数 == 1) then (true)
		: 合致したブロックを運搬対象ブロックとする;
	else if(個数 > 1) then (true)
		: 合致したブロックのうち、ロボットの位置から最も近い位置に存在するブロックを運搬対象ブロックとする;
	else
		: 一時退避するブロックを決定する;
		if(赤の置き場に、黒ブロックまたは赤ブロック以外が置かれている) then (true)
			:赤の置き場に置かれているブロックを運搬対象ブロックとする;
		else (else)
			:ブロックの色と置き場の色が一致していないブロックのうち、\nロボットの位置から最も近い位置に存在するブロックを運搬対象ブロックとする;
		endif
	endif
}	

partition 運搬先の置き場を決定する {
	:運搬対象のブロックと一致するブロック置き場を探索する;
	if(個数==1) then (true)
		: 合致した置き場を運搬先の置き場とする;
	else if(個数 > 1) then (true)
		: 合致した置き場のうち、\nブロックの座標から最も近い位置のブロック置き場を運搬先の置き場とする;
	else
		: 退避先の置き場を選ぶ;
		: ブロックの座標から最も近い位置のブロック置き場を運搬先の置き場とする;
	endif
}


@enduml