@startuml

title ブロック運び状態遷移図


state ブロックまで移動 {
	ウェイポイント移動中 : entry / 次のウェイポイントまでの向きと距離を計算する
	ウェイポイント移動中 : do / 自己位置を推定しながら移動する


	ライントレース中 : entry / ラインの向きに旋回する
	ライントレース中 : do / ラインに沿って移動する
	ライントレース中 : exit / 停止する


	[*] --> ウェイポイント移動中

	ウェイポイント移動中--> ライントレース中 : 最終ウェイポイント到達
	ウェイポイント移動中 --> ウェイポイント移動中 : 途中ウェイポイント到達

	ライントレース中 --> [*] : 置き場到達
}

state ブロックを運搬{
	ウェイポイント移動中_ : entry / 次のウェイポイントまでの向きと距離を計算する
	ウェイポイント移動中_ : do / 自己位置を推定しながら移動する


	ライントレース中_ : entry / ラインの向きに旋回する
	ライントレース中_ : do / ラインに沿って移動する
	ライントレース中_ : exit / 停止する


	[*] --> ウェイポイント移動中_

	ウェイポイント移動中_ --> ライントレース中_ : 最終ウェイポイント到達
	ウェイポイント移動中_ --> ウェイポイント移動中_ : 途中ウェイポイント到達

	ライントレース中_ --> [*] : 置き場到達
}

[*] --> ブロックまで移動

ブロックまで移動 --> ブロックを運搬
ブロックを運搬 --> ブロックをパージ

ブロックをパージ --> ブロックまで移動 : 五角形が完成していない場合
ブロックをパージ --> [*] : 五角形が完成した場合


@enduml