@startuml

title ブロック並べ状態遷移図

state ブロックまで移動 {
	ウェイポイント移動中 : entry / 次のウェイポイントの角度に旋回
	ウェイポイント移動中 : do / 自己位置推定結果を補正しながら移動

	ライントレース中 : entry / ラインの向きに旋回する
	ライントレース中 : do / ラインに沿って移動する
	ライントレース中 : exit / 停止する

	[*] --> ウェイポイント移動中

	ウェイポイント移動中--> ライントレース中 : 最終ウェイポイント到達
	ウェイポイント移動中 --> ウェイポイント移動中 : 途中ウェイポイント到達

	ライントレース中 --> [*] : ポリゴンブロック置き場到達
}

state ブロックを運搬{
	ウェイポイント移動中_ : entry / 次のウェイポイントの角度に旋回
	ウェイポイント移動中_ : do / 自己位置推定結果を補正しながら移動

	ライントレース中_ : entry / ラインの向きに旋回する
	ライントレース中_ : do / ラインに沿って移動する
	ライントレース中_ : exit / 停止する

	[*] --> ウェイポイント移動中_

	ウェイポイント移動中_ --> ライントレース中_ : 最終ウェイポイント到達
	ウェイポイント移動中_ --> ウェイポイント移動中_ : 途中ウェイポイント到達

	ライントレース中_ --> [*] : ポリゴンブロック置き場到達
}

[*] --> ブロックまで移動

ブロックまで移動 -ri-> ブロックを運搬
ブロックを運搬 --> ブロックを離す

ブロックを離す --> ブロックまで移動 : 全ての運搬コマンドが完了していない場合
ブロックを離す --> [*] : 全ての運搬コマンドが完了した場合


@enduml