@startuml
title <size:18>ブロック運びフローチャート</size>


start
: 初期位置の算出;
: 運搬ルールの生成;

repeat :運搬ルール生成;
	:運搬対象ブロックの決定;
	:運搬先ポリゴンブロック置き場の決定;
	:運搬経路の決定;
repeat while (全ての運搬ルール生成終了);

repeat :運搬ルール実行;
	:運搬ルールの読み込み;
	:運搬対象ブロックの確保;
	:運搬対象ブロックの運搬;
	:ブロックと置き場の情報更; 
repeat while (全ての運搬ルール実行終了);

stop


@enduml