@startuml

title モニタツールを構成するクラス(抜粋)

 
package ブロック並べ攻略{
    class フィールド{

    }

    class ブロック運搬ルール導出{
        五角形を構成するポリゴンブロック置き場のNo
        ブロック運搬ルール生成(初期位置コード)
    }

    class ブロック運搬コマンド{

    }

    ブロック運搬コマンド "1"-->"2..*" ライン : ブロックの確保/運搬で移動する経路
    ブロック運搬コマンド "1"-->"2" ポリゴンブロック置き場 : 運搬元/運搬先

    class ポリゴンブロック置き場{
        番号
        座標
        色
        移動完了判定()
        他の置き場との距離(ポリゴンブロック置き場)
        走行体との距離(走行体)
    }
    
    class ブロック {
        色
        運搬済み
    }

    ポリゴンブロック置き場 "1" --> "0..1" ブロック

    class ブロック運搬ルール {

    }

    ブロック運搬ルール導出 ..> ブロック運搬ルール
    ブロック運搬ルール "1" --> "5...*" ブロック運搬コマンド

    ブロック運搬ルール導出 "1" --> フィールド
    フィールド  "1" -->"26" ライン
    フィールド "1" --> "15" ポリゴンブロック置き場
 
    class ライン{
        番号Slack
        長さ
        角度
        ウェイポイント座標
        経由可能なライン番号[]
    }

    ライン "1" --> "2" ポリゴンブロック置き場 : 始点/終点 
    class ダイクストラ法{
        最短経路算出()
    }
    
    ダイクストラ法 "1" ->  "1" フィールド
  
    class 走行体 {
        座標
        走行体座標更新(座標)
    }

    ブロック運搬ルール導出 "1" --> "1" 走行体
    ブロック運搬ルール導出 "1" --> "1" ダイクストラ法

}



@enduml