@startuml
title <size:18>運搬対象ブロックの決定</size>

partition 運搬対象ブロックを決定する {
	:運搬可能なブロックを探索する;
	if(個数 == 1) then (true)
		: 合致したブロックを運搬対象ブロックとする;
	else if(個数 > 1) then (true)
		: 合致したブロックのうち、ロボットの位置から最も近い位置に存在するブロックを運搬対象ブロックとする;
	else
		: 一時退避するブロックを決定する;
		if(赤の置き場に、黒ブロックまたは赤ブロック以外が置かれている) then (true)
			:赤の置き場に置かれているブロックを運搬対象ブロックとする;
		else (else)
			:ブロックの色と置き場の色が一致していないブロックのうち、\nロボットの位置から最も近い位置に存在するブロックを運搬対象ブロックとする;
		endif
	endif
}	



@enduml