'信号 -- 電圧/パルス/ON-OFF'
'電文 -- バイトデータの羅列'

@startuml
title << ユースケース図_TK-Rプロトタイプ作成 >>

'left to right direction

actor   チームメンバー
entity  走行ログ

package モニタツール{
    boundary    仮想シリアル_Mon
    boundary    描画ソフトウェア    

    描画ソフトウェア <- 仮想シリアル_Mon : 出力信号情報
}

package シミュレータツール{
    boundary    シミュレータソフトウェア
    boundary    仮想シリアル_Sim
    シミュレータソフトウェア -> 仮想シリアル_Sim : 入力信号情報
    シミュレータソフトウェア <- 仮想シリアル_Sim : 出力信号情報

}

package 模擬HILSコンソール{
    boundary    仮想シリアル1
    boundary    走行アルゴリズム
    boundary    仮想シリアル2
    
    走行アルゴリズム <- 仮想シリアル1 : 入力信号情報
    走行アルゴリズム -> 仮想シリアル1 : 出力信号情報

    仮想シリアル2 <- 走行アルゴリズム : 出力信号情報
}

仮想シリアル_Sim -> 仮想シリアル1 : 入力信号電文
仮想シリアル_Sim <- 仮想シリアル1 : 出力信号電文

仮想シリアル_Mon <- 仮想シリアル2 : 入力信号電文
仮想シリアル_Mon <- 仮想シリアル2 : 出力信号電文

チームメンバー -> シミュレータソフトウェア : 状態確認

チームメンバー -> 描画ソフトウェア : 状態確認
チームメンバー -> 描画ソフトウェア : 状態操作
描画ソフトウェア -> 走行ログ : 出力

@enduml