@startuml
title << ユースケース図 >>

left to right direction

actor   競技者

package システム {
	usecase	スピード競技を攻略する
	usecase	ブロック並べを攻略する
	usecase 縦列駐車を攻略する

}

競技者 --> スピード競技を攻略する
競技者 --> ブロック並べを攻略する
競技者 --> 縦列駐車を攻略する

@enduml