@startuml

title Bluetooth通信機器のモニタツールを構成するパッケージ構成

package Bluetooth通信{

}

package ユーザーインターフェース {
}


package ブロック並べ攻略 {
}


ユーザーインターフェース ..> Bluetooth通信  : ブロック運搬コマンド及びPIDパラメータの送信
ユーザーインターフェース ..> ブロック並べ攻略 : ブロック運搬コマンドの取得



@enduml